// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeMZMaXGDDojb-F3qxB4JUvsWZUiV7mKg',
    appId: '1:391402314875:web:49fcfd3cf98eaed4dc56de',
    messagingSenderId: '391402314875',
    projectId: 'ckd-care',
    authDomain: 'ckd-care.firebaseapp.com',
    storageBucket: 'ckd-care.appspot.com',
    measurementId: 'G-ZSRZ23DHYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFfIRKCHd6vh5yfv7qOqmpQgbhNLu2sYY',
    appId: '1:391402314875:android:7ae78679262ebb72dc56de',
    messagingSenderId: '391402314875',
    projectId: 'ckd-care',
    storageBucket: 'ckd-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEGUPhMIqs1Yf6QWQdPnulIe7V6Ok1NvA',
    appId: '1:391402314875:ios:241c22f928c11f7ddc56de',
    messagingSenderId: '391402314875',
    projectId: 'ckd-care',
    storageBucket: 'ckd-care.appspot.com',
    androidClientId: '391402314875-tl11ia4r6sgskqd4lrendg18ss7vlf3b.apps.googleusercontent.com',
    iosClientId: '391402314875-masv31nbg3qkojcek6ug8am754kms0rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEGUPhMIqs1Yf6QWQdPnulIe7V6Ok1NvA',
    appId: '1:391402314875:ios:241c22f928c11f7ddc56de',
    messagingSenderId: '391402314875',
    projectId: 'ckd-care',
    storageBucket: 'ckd-care.appspot.com',
    androidClientId: '391402314875-tl11ia4r6sgskqd4lrendg18ss7vlf3b.apps.googleusercontent.com',
    iosClientId: '391402314875-masv31nbg3qkojcek6ug8am754kms0rq.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdsc',
  );
}
