// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVigPhLOOb_Xz3OS3F7wkGC5pc17XDeEo',
    appId: '1:428554762480:web:2f81d19ec3bf66ad196a35',
    messagingSenderId: '428554762480',
    projectId: 'yozicare-ae4be',
    authDomain: 'yozicare-ae4be.firebaseapp.com',
    storageBucket: 'yozicare-ae4be.appspot.com',
    measurementId: 'G-P36JZZ9DD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKgTmM6VDf9qRA-uRrOxnu2TcyX9__lYI',
    appId: '1:428554762480:android:619f59ffcc99f8cc196a35',
    messagingSenderId: '428554762480',
    projectId: 'yozicare-ae4be',
    storageBucket: 'yozicare-ae4be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFWS9pit3U90EoM0f-7fqtB1adwq2dyM',
    appId: '1:428554762480:ios:8006bf9b5e521975196a35',
    messagingSenderId: '428554762480',
    projectId: 'yozicare-ae4be',
    storageBucket: 'yozicare-ae4be.appspot.com',
    iosClientId: '428554762480-knohvr9vnlj1vbdbeshnk3ffu5tbb7lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdsc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxFWS9pit3U90EoM0f-7fqtB1adwq2dyM',
    appId: '1:428554762480:ios:8006bf9b5e521975196a35',
    messagingSenderId: '428554762480',
    projectId: 'yozicare-ae4be',
    storageBucket: 'yozicare-ae4be.appspot.com',
    iosClientId: '428554762480-knohvr9vnlj1vbdbeshnk3ffu5tbb7lr.apps.googleusercontent.com',
    iosBundleId: 'com.example.gdsc',
  );
}
